before_build:
  - nuget restore sem2/hw1/Factorial.sln
  - nuget restore sem2/hw1.4/hw1.4.sln
  
build:
  project: sem2/hw1/Factorial.sln
          
build:
  project: sem2/hw1.4/hw1.4.sln
  
test_script:
